### ISSUE TITLE
Plugin messing with the number of intellisense options shown in the editor

### ISSUE THREAD

**Issue by irisida** [sendhil/vscode-file-explorer-menu#2]
Hi, 
Firstly, cool plugin, I love nerdtree and this is what I was looking for, however I believe the current version is screwing with the number of intellisense options that a user is shown after installation of the plugin. 

Please see a screenshot of the editor intellisense options showing only two options when typically it shows multiple. 
![report1](https://user-images.githubusercontent.com/20445648/99882632-e43dec00-2c19-11eb-8857-ea59e4ba3b97.png)

I then disabled the plugin and rechecked. 
![report2](https://user-images.githubusercontent.com/20445648/99882644-ff106080-2c19-11eb-9868-82832db87d8b.png)
![report3](https://user-images.githubusercontent.com/20445648/99882646-0172ba80-2c1a-11eb-810a-509e4e46a937.png)

So I then re-enabled the plugin again. 
![report4](https://user-images.githubusercontent.com/20445648/99882666-1b140200-2c1a-11eb-8247-1be57ddbb25f.png)

Disable again, no restart. 
![report5](https://user-images.githubusercontent.com/20445648/99882670-25ce9700-2c1a-11eb-84cd-f1d6d445eb42.png)

I can't see any documented property that allows me to configure that and I don't see it documented as a feature. Therefore, please accept the bug raised.

Trivial golang code used to test.
```go
package main

import (
	"fmt"
	"runtime"
)

func main() {

	fmt.Println("Main execution started...")
	fmt.Println("No of CPUs : ", runtime.NumCPU())
	fmt.Println("No of goroutines: ", runtime.NumGoroutine())

	fmt.Println("OS: ", runtime.GOOS)
	fmt.Println("ARCH: ", runtime.GOARCH)

        // line used to test the trigger of intellisense options being displayed 
	// fmt.p
}
```

**Comment by sendhil** [comment]
Hi @irisida - thanks for using the plugin and for the bug report. I think this might be because you are doing `fmt.` vs `fmt.P` in those screenshots.  

![image](https://user-images.githubusercontent.com/437043/99883599-61973b80-2bdd-11eb-82a9-3164bfd57b14.png)

Using the example you provided, I tried to replicate the issue and I was as unable to reproduce it. Here's a few screenshots of my attempt:

**Plugin Enabled** -  fmt.
![fmtdot](https://user-images.githubusercontent.com/437043/99883480-a2428500-2bdc-11eb-927b-ae2c9fb26267.png)

**Plugin Enabled** -  fmt.P
![fmtdotp](https://user-images.githubusercontent.com/437043/99883492-b1293780-2bdc-11eb-9b82-c26674a16bc7.png)

**Plugin Disabled** - fmt.
![disabledfmtdog](https://user-images.githubusercontent.com/437043/99883502-bf775380-2bdc-11eb-9f61-5fae214e1ae2.png)

**Plugin Disabled** - fmt.P
![disabledfmtdotp](https://user-images.githubusercontent.com/437043/99883506-c4d49e00-2bdc-11eb-9c0b-c274d1e4a7ee.png)

Here's small video of me doing the same:
![Trying to Reproduce Bug](https://user-images.githubusercontent.com/437043/99883629-87244500-2bdd-11eb-9a25-14d74edeefc4.gif)

If there's something I missed with how I reproduced it let me know and I'll try again, but in the mean time, could you retry and see if the issue happens when you do `fmt.` vs `fmt.P`?

**Comment by irisida** [comment]
Hi 
Thanks for the response. For me, the issue persisted. Interestingly enough, under a myriad of testing conditions, I believe the source of the issue is with the vim plugin (vscodevim) and not yours. The issue became intermittent, on issue occasions where only 1 or 2 IntelliSense options were presented, backtracking to 'fmt' then adding the '.' again would present the fuller list (the expected condition)

I tried various permutations of enabling/disabling plugins but couldn't determine 'the one' that when added to the pile would cause the issue. Other possible false flags were the window zoom level settings, with a higher reoccurrence rate when the window zoom level was set to -1.0 than when set to -0.6. 

In the end I was fully-backed up, had nothing lingering on the machine that was irreplaceable, so I blitzed the machine (2015 MBP 16GB, i7 on 10.15.7) and reset it about 4am this morning and installed nothing except vscode, vim and your plugin. I'll run it a couple of days as I slowly reintroduce the other plugins I use and see if I can find the one that adds enough beef that vscodevim craps the bed again. 

If all else fails its alacrity, neovim and nerdtree. 

Best wishes

**Comment by irisida** [comment]
![reinstall1](https://user-images.githubusercontent.com/20445648/99906374-b23a9180-2cce-11eb-96a5-7cd213756cf5.png)

see the full list above, expected... and behold the small 'p' below.... 

![reinstall2](https://user-images.githubusercontent.com/20445648/99906388-c54d6180-2cce-11eb-9d28-e7ec4475f763.png)

**Comment by irisida** [comment]
Moved to close.
